# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
