# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-25 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180514_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
